### ISSUE TITLE
Do developers want to identify when a device is being used with a pen / drawing posture?

### ISSUE THREAD

**Issue by diekus** [diekus/screen-fold#96]
From TPAC 2021 the question came regarding being able to identify when a device is being used in a posture that enables drawing.  At the moment it is possible to detect when a device is being used primarily with touch input, but there is no way of identifying if pen is present.

**Comment by chris480** [comment]
I thought PointerEvent.pointerType would inform the browser of this?

**Comment by darktears** [comment]
Pen events are delivered through PointerEvents. Most of the styluses around do not have a permanent connection with the device (I think the Surface Pen does with some Bluetooth), the OS only knows about them when they come in proximity of the touch digitizer. There isn't a way to know if the stylus is the primary input because it can come and go at any time and user can use the touch screen.

Now comes the real question, what UX changes would you trigger if you know the primary input is a stylus and not touch or mouse?

**Comment by voxpelli** [comment]
> what UX changes would you trigger if you know the primary input is a stylus and not touch or mouse

A stylus has the precision of the mouse but the behavior of touch, with exceptions:

- Some stylus can hover
- Some stylus has pressure sensitivity
- Some stylus has buttons or other alternative interactions (like an eraser)

If stylus is primary input: Then I might make click targets smaller, might use hover in the UX

I think PointerEvents and the `hover` + `pointer` media queries already provide enough info for adapting the UX?

**Comment by darktears** [comment]
@voxpelli I'm familiar with what you said and the basic premise of a stylus. All your bullet points are covered with the PointerEvents.

Now my comment was about "if stylus is the primary input" and UX changes. Let's step back. How an OS/Device can determine if the stylus is the primary input provided that the moment it goes out of range (few centimeters) the OS can't see it, but it can come back anytime (meaning the user is just lifting its palm). The hover feature works only with very close proximity of the screen. Therefore, changing the UX doesn't make sense because it will keep wobbling between stylus-primary to touch-primary. 

Microsoft can comment but even if the stylus entertains some bluetooth connection it's only to enable gestures like double click to launch an app (even if you're not in close proximity of the touch digitizer). All the event delivery is done through the digitizer therefore suffering the same limitation as I describe above.

**Comment by voxpelli** [comment]
👍 I believe the [`any-hover`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover) / [`any-pointer`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-pointer) therefore could be more suitable, if the system is allowed to do some guessing on the likelihood of a stylus appearing or not.

(As a web developer I'm not too familiar with the exact spec formulations, but wanted to add my 2 cents, especially as not many others had elaborated here ☺️)

**Comment by darktears** [comment]
No worries, I think I clarified with @diekus so maybe he can close the issue.
